name: Package Manifest Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  package-json-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Lint package manifests
        run: yarn lint:package-json
